# Generated by Django 5.0.7 on 2024-08-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('6601', 'Category 6601'), ('7051', 'Category 7051'), ('8849', 'Category 8849')], default='6601', max_length=4),
        ),
        migrations.AddField(
            model_name='task',
            name='particulate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='requested_test_count',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')], default=1),
        ),
        migrations.AddField(
            model_name='task',
            name='test_count',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')], default=1),
        ),
    ]
