# Generated by Django 5.0.7 on 2024-08-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_task_category_task_particulate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='base_value',
            field=models.FloatField(default=0.0, help_text='Valor base para cálculo'),
        ),
        migrations.AddField(
            model_name='task',
            name='calculated_value',
            field=models.FloatField(default=0.0, editable=False, help_text='Valor calculado com base em base_value'),
        ),
    ]
